### ISSUE TITLE
Console Error with CMI

### ISSUE THREAD

**Issue by Feldmarschall** [ChanceSD/PvPManager-Issues#176]
```
[11:06:45 ERROR]: Could not pass event EntityDamageByEntityEvent to PvPManager v3.19.2
java.lang.NoSuchMethodError: 'java.lang.Boolean com.Zrips.CMI.Containers.CMIUser.isGod()'
        at nc.dG.a(SourceFile:28) ~[PvPManager-3.19.2.jar:?]
        at nc.eX.a(SourceFile:178) ~[PvPManager-3.19.2.jar:?]
        at nc.eF.a(SourceFile:197) ~[PvPManager-3.19.2.jar:?]
        at nc.eF.a(SourceFile:171) ~[PvPManager-3.19.2.jar:?]
        at nc.eF.d(SourceFile:145) ~[PvPManager-3.19.2.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-448]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.3.jar:git-Paper-448]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.3.jar:git-Paper-448]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:250) ~[paper-1.19.3.jar:git-Paper-448]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1154) ~[paper-1.19.3.jar:git-Paper-448]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1013) ~[paper-1.19.3.jar:git-Paper-448]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:965) ~[paper-1.19.3.jar:git-Paper-448]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1188) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2150) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1385) ~[?:?]
        at net.minecraft.world.entity.player.Player.attack(Player.java:1314) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2118) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:2842) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2766) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1445) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-448]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Plugin and Server version**
Paper-448 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 155aa36)
PvPManager 3.19.2

**Comment by ChanceSD** [comment]
I haven't tested it yet, but CMI recently posted an update "Fix for issue with API calls.." that might solve this. Give it a try if you can:
https://www.spigotmc.org/resources/cmi-298-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much-more.3742/update?update=493083

**Comment by PuppyNomNom** [comment]
The CMI update doesn't fix this. I just tested

**Comment by ChanceSD** [comment]
I will make an update soon, if anyone needs a quick fix just change "Disable Godmode" to false in the config
