### ISSUE TITLE
Players get kicked after pvp due to some team issues

### ISSUE THREAD

**Issue by PixelsTurtle** [ChanceSD/PvPManager-Issues#195]
**Describe the bug**
Basically, players will get kicked once anyone start pvp and ends it. It only kicks players when the pvp grace period thingy is over.

**To Reproduce**
1. Start pvping someone 
2. Wait for the grace period to end
3. Everyone gets kicked

**Expected behavior**
I expect the players to not get kicked and play as they should

**Plugin and Server version**
'PvPManager-3.34.37' 
'Pufferfish 1.21.1'

```
---- Minecraft Network Protocol Error Report ----
// I heard pigeons are more reliable

Time: 2024-12-15 15:22:19
Description: Packet handling error

java.lang.IllegalStateException: Player is either on another team or not on any team. Cannot remove from team 'PVP-b2c09356070b'.
	at knot//net.minecraft.class_269.method_1157(class_269.java:308)
	at knot//net.minecraft.class_634.method_11099(class_634.java:2050)
	at knot//net.minecraft.class_5900.method_34173(class_5900.java:132)
	at knot//net.minecraft.class_5900.method_11054(class_5900.java:18)
	at knot//net.minecraft.class_2600.method_11072(class_2600.java:27)
	at knot//net.minecraft.class_1255.method_18859(class_1255.java:162)
	at knot//net.minecraft.class_4093.method_18859(class_4093.java:23)
	at knot//net.minecraft.class_1255.method_16075(class_1255.java:136)
	at knot//net.minecraft.class_1255.method_5383(class_1255.java:121)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1240)
	at knot//net.minecraft.class_310.method_1514(class_310.java:882)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at knot//net.minecraft.class_269.method_1157(class_269.java:308)

-- Incoming Packet --
Details:
	Type: clientbound/minecraft:set_player_team
	Is Terminal: false
	Is Skippable: false
Stacktrace:
	at knot//net.minecraft.class_2600.method_59803(class_2600.java:56)
	at knot//net.minecraft.class_8673.method_60882(class_8673.java:136)
	at knot//net.minecraft.class_8673.method_59807(class_8673.java:113)
	at knot//net.minecraft.class_2600.method_11072(class_2600.java:32)
	at knot//net.minecraft.class_1255.method_18859(class_1255.java:162)
	at knot//net.minecraft.class_4093.method_18859(class_4093.java:23)
	at knot//net.minecraft.class_1255.method_16075(class_1255.java:136)
	at knot//net.minecraft.class_1255.method_5383(class_1255.java:121)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1240)
	at knot//net.minecraft.class_310.method_1514(class_310.java:882)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Connection --
Details:
	Protocol: play
	Flow: CLIENTBOUND
	Server type: OTHER
	Server brand: Pufferfish

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 930273872 bytes (887 MiB) / 3351248896 bytes (3196 MiB) up to 6274678784 bytes (5984 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 3700X 8-Core Processor             
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.59
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3070
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 8192.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.6094
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 46359.25
	Virtual memory used (MiB): 35354.59
	Swap memory total (MiB): 30063.32
	Swap memory used (MiB): 5093.14
	Space in storage for jna.tmpdir (MiB): available: 68029.21, total: 953238.31
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 68029.21, total: 953238.31
	Space in storage for io.netty.native.workdir (MiB): available: 68029.21, total: 953238.31
	Space in storage for java.io.tmpdir (MiB): available: 68029.21, total: 953238.31
	Space in storage for workdir (MiB): available: 68029.21, total: 953238.31
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5984m -Xms256m
	Fabric Mods: 
		axiom: Axiom 4.2.0
			com_moulberry_axiomclientapi_axiomclientapi_: axiomclientapi 1.0.0
			com_moulberry_mixinconstraints: mixinconstraints 1.0.1
		cloth-config: Cloth Config v15 15.0.140
			cloth-basic-math: cloth-basic-math 0.6.1
		damagenumbers: Damage Numbers 1.4.1-fabric
		distanthorizons: Distant Horizons 2.2.0-a
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c90
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a790
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b559734490
		entityculling: EntityCulling 1.7.0
		fabric-api: Fabric API 0.102.0+1.21
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bcd1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366fd1
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd9d1
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.19+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.5.0+c5e2b5c6d1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.27+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.16+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.12+ba9dae06d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd9d1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.4+78017270d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df360d1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a5d1
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a5d1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.2+60c3209bd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.0+a551f7a4d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.12+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.2+60c3209bd1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49cd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49cd1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd0d1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b1d1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+56599129d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.86+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.16+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+176f9036d1
		fabric-language-kotlin: Fabric Language Kotlin 1.12.3+kotlin.2.0.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.9.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.9.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.3
		fabricloader: Fabric Loader 0.16.7
			mixinextras: MixinExtras 0.4.1
		figura: Figura 0.1.5-rc.1+1.21
			com_github_figuramc_luaj_luaj-core: luaj-core 3.0.8-figura
			com_github_figuramc_luaj_luaj-jse: luaj-jse 3.0.8-figura
			com_neovisionaries_nv-websocket-client: nv-websocket-client 2.14
		flashback: Flashback 0.11.0
			mixinsquared: MixinSquared 0.2.0-beta.6
		freecam: Freecam 1.3.0+mc1.21
		invmove: InvMove 0.8.8
		iris: Iris 1.8.0-beta.4+mc1.21.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		itemscroller: Item Scroller 0.24.50
		java: OpenJDK 64-Bit Server VM 21
		justzoom: Just Zoom 2.0.0
		konkrete: Konkrete 1.9.9
		litematica: Litematica 0.19.50
		macrokeybinds: Macro Keybinds 1.3.1
		malilib: MaLiLib 0.21.0
		minecraft: Minecraft 1.21
		minihud: MiniHUD 0.32.50
		modmenu: Mod Menu 11.0.3
		mousetweaks: Mouse Tweaks 2.26
		nbttooltip: NBT Tooltip 1.2.0
		owo: oωo 0.12.15+1.21
			blue_endless_jankson: jankson 1.2.2
			io_wispforest_endec: endec 0.1.5
			io_wispforest_endec_gson: gson 0.1.3
			io_wispforest_endec_jankson: jankson 0.1.3
			io_wispforest_endec_netty: netty 0.1.2
		placeholder-api: Placeholder API 2.4.1+1.21
		screenshotclipboard: Screenshot to Clipboard 1.0.10
		shulkerboxtooltip: Shulker Box Tooltip 5.1.1+1.21
		sodium: Sodium 0.6.0-beta.2+mc1.21.1
		soundboard-svc: Voice Chat Soundboard 0.7.0
			kowoui: Kotlin OwO UI 0.3.0
			soundboard-core: Soundboard Core 0.7.0
				com_squareup_okhttp3_okhttp: okhttp 4.12.0
				com_squareup_okio_okio-jvm: okio-jvm 3.9.1
		voicechat: Simple Voice Chat 1.21.1-2.5.26
	Loaded Shaderpack: (off)

```

**Comment by PixelsTurtle** [comment]
```
5:30:46] [Server thread/INFO]: [PvPManager] Enabling PvPManager v3.34.37
[15:30:46] [Server thread/INFO]: [PvPManager] Using player nametags: true
[15:30:46] [Server thread/INFO]: [com.zaxxer.hikari.HikariDataSource] 
 - Starting...
[15:30:46] [Server thread/INFO]: [com.zaxxer.hikari.pool.HikariPool] PvPManager - Added connection org.sqlite.jdbc4.JDBC4Connection@58629ff5
[15:30:46] [Server thread/INFO]: [com.zaxxer.hikari.HikariDataSource] PvPManager - Start completed.
[15:30:46] [Server thread/INFO]: [PvPManager] Connected to SQLITE database successfully
[15:30:46] [Server thread/INFO]: [PvPManager] Players stored: 14
[15:30:46] [Server thread/INFO]: [PvPManager] WorldGuard Found! Enabling Support For WorldGuard Regions
[15:30:46] [Server thread/INFO]: [PvPManager] Essentials Found! Hooked successfully
[15:30:46] [Server thread/INFO]: [PvPManager] Vault Found! Using it for currency related features
[15:30:46] [Server thread/INFO]: [PvPManager] PlaceholderAPI Found! Hooked successfully
[15:30:46] [Server thread/INFO]: [PlaceholderAPI] Successfully registered internal expansion: pvpmanager [3.34.37]
[15:30:46] [Server thread/INFO]: [PvPManager] LibsDisguises Found! Using it to disable disguises
[15:30:46] [Server thread/INFO]: [PvPManager] GriefPrevention Found! Enabling borders and checking conflicting settings
[15:30:46] [Server thread/WARN]: [PvPManager] GriefPrevention has some combat features without showing any feedback messages. Make sure to set PunishLogout to false and set CombatTimeoutSeconds to 0 seconds in GP config. Conflicts with those features often get wrongly blamed on PvPManager due to lack of GP feedback messages.
[15:30:46] [Server thread/ERROR]: [PvPManager] You have kill on logout enabled in PvPManager, so we automatically disabled the same feature on GriefPrevention. Disable this setting in GP or  to remove this error, this is necessary as it will cause issues.
[15:30:46] [Server thread/INFO]: [PvPManager] NPC spawning is supported in this version! (1.21.1)
[15:30:46] [Server thread/INFO]: [PvPManager] Starting border task with radius 6 and rate of 150ms
[15:30:46] [Server thread/INFO]: [PvPManager] PvPManager v3.34.37 enabled (456 ms)
```

**Comment by PixelsTurtle** [comment]
CONFIG:

```
# +--------------------------------------------------------------------------+ #
# <                  PvPManager Premium Configuration File                   > #
# <--------------------------------------------------------------------------> #
# <                If you have any questions please go to                    > #
# <           https://www.spigotmc.org/resources/pvpmanager.10610            > #
# <                  or Discord https://discord.gg/QFTjs3g                   > #
# +--------------------------------------------------------------------------+ #

# Player instantly respawns after death! (Only version 1.8.8+)
Auto Respawn: false

# Default PvP -> Leave it at true unless you want no PvP for new players
# Extra Protection -> Prevent players from placing lava or fire near pvp disabled players
# PvP Blood -> Enable blood particles on PvP
# Player Drop Mode -> What happens to a player's drops and exp on death
# The options are 'ALWAYS' - (PvPManager does nothing, so feature is disabled),
# mode 'DROP' - (Players drop items when killed in PvP but not in PvE),
# mode 'KEEP' - (Players keep items when killed in PvP but not in PvE) and
# mode 'TRANSFER' - (Same as 'DROP' but transfer items(not exp) directly to killer's inventory without drops)
# mode 'CLEAR' - (Clear all drops and exp on death, this deletes everything on death so make sure it is what you want)
# Ignore No Damage Hits -> Ignore hits from snowballs, eggs, fishing rod and others
# World Exclusions -> List of worlds where PvPManager will have no effect
General:
  # Changes messages language, options are - EN | BG | DE | ES | FI | FR | HR | IT | JA | KO | PL | pt_BR | RU | TR | zh_TW | ZH
  Locale: EN
  Default PvP: false
  Extra Protection: true
  PvP Blood: true
  Player Drop Mode: ALWAYS
  # If true all deaths while combat tagged are considered PvP deaths since the player is fighting someone
  Deaths While Tagged Count PvP: true
  Ignore No Damage Hits: true
  Auto Soup:
     # How much health does soup heal, use 0 to disable
     Health: 0
     # Should empty bowls just be deleted
     Bowl Disappear: false
  # Removes empty potion bottles and milk buckets after they are consumed
  Recycling:
    Potion Bottle: false
    Milk Bucket: false
  World Exclusions:
    - 'example'
    
# Here you can choose which methods to use to stop 'border hopping' while players are tagged
# Border hopping is when a player gets in PvP and tries to run into a safe zone to escape
# The pushback feature currently supports regions from WorldGuard, Griefprevention, Towny and Lands
Anti Border Hopping:
  # Makes players still vulnerable to PvP in safe zones
  Vulnerable: false
  # Generate a block barrier when trying to enter a safezone. Recommended to use together with PushBack enabled
  Barrier:
    Enabled: true
    # Options are FAST or FULL mode, FAST is recommended even though FULL covers more angles
    Mode: FAST
    # You can use any block from here - https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
    Material: RED_STAINED_GLASS
    # Distance to check around the player
    Radius: 6
    # How often to update the barrier, default is every 3 ticks = 150ms
    Update Rate: 3
  # Players will be launched back when trying to enter a safe zone
  Push Back:
    Enabled: true
    # How much force for the pushback (Minimum 0.1 and Maximum 4)
    Force: 1.2
    # Block attempts to enter a safe zone with enderpearls while tagged
    Block EnderPearl: true
    # Shows a text hologram when the player gets pushed back (MC 1.19.4+)
    Hologram Display: true
    # Takes elytra from player chest slot and puts it in their inventory
    Remove Elytra: false
  # Only meant for when Vulnerable is true. Toggles whether combat tagging resets while fighting in a safe zone. Works for WorldGuard Only
  Reset Combat Tag: true
  # Name of regions where vulnerable will have no effect
  WorldGuard Exclusions:
    - 'example'

# What should be disabled when a player(except operators) enters PvP
# Fly -> Disable any kind of fly mode
# GameMode -> Anything not Survival gets disabled
# Disguise -> Disguises from LibsDisguises
# GodMode -> GodMode from Essentials or CommandBook
# Invisibility -> Invisibility potions, defaults to false as it's a vanilla feature
Disable:
  Fly: true
  GameMode: true
  Disguise: true
  GodMode: true
  # Makes player fall down if they're tagged while elytra gliding
  Elytra: false
  Invisibility:
    Remove from Attacker: false
    Remove from Defender: false

# Section about the combat tag system
# PvE Tag -> If damage from or to monsters and animals should tag the player
# Only Hostile -> If true, only monsters will tag the player, otherwise all animals will tag the player
# Any Damage -> If anything else that can damage a player like lava, falling, etc should tag them
# Time -> How long should the tag last in seconds
# NameTag Prefix -> Choose the player's nametag prefix while tagged, '&c' would just color their name red
# while empty quotes '' will disable this feature completely
# Glowing -> For 1.9+ only, sets the player glowing while tagged
# Self Tag -> Allow players to tag themselves with a bow
# Untag Enemy -> When the player kills the enemy he was fighting he gets untagged
# Block -> Section is self-explanatory, what to block in combat
# Command whitelist is recursive, allowing 'tell' will allow 'tell' with any number of arguments
# Commands On Tag -> Commands executed as the player when tagged, this allows for huge customization
# WorldGuard Exclusions -> Name of regions where players will not get tagged
# Punish On Kick -> Punish the player even if he gets kicked by other plugin while tagged
# Money Penalty -> Money lost on combat log, use less or equal to 1 for percentage like 0.05 for 5%, 1 for 100% (0 to disable)
# Log To File -> Logs all combat loggers to a file that you can read later
# Money Penalty -> Money lost on combat log, use less than 1 for percentage like 0.05 for 5% (0 to disable)
# Kill on Logout -> Setting this to true will do nothing if NPCs are enabled
# Spawn NPC -> Will spawn an NPC with the player's items which will drop as a normal player would
# NPC Name -> Leave empty to use player name or write a name for all NPCs like 'Logger' Max length is 16 characters
# NPC Despawn Time -> Time until NPC automatically despawns
# Block Login -> Block player from logging in while their NPC is spawned
# Spawn On All Logouts -> Spawns an NPC on every player logout even if not in combat
# No Spawn In WorldGuard -> If enabled, NPC won't be spawned in regions with pvp deny
# Drops On Death - Controls what will drop when a player that PvP Logged or his NPC are killed
# Commands On PvPLog -> List of commands to execute on combat log, use '%p' for player name
# And use the 'announce' command to broadcast, to disable just delete the command
Tagged In Combat:
  Enabled: true
  PvE Tag:
    Enabled: false
    Only Hostile: true
    Any Damage: false
  Time: 10
  NameTag Prefix: '&4&l&c'
  # Only when using the TAB plugin
  NameTag Suffix: ''
  Glowing: true
  Action Bar:
    Enabled: false
    # You can use any PlaceholderAPI placeholders here
    Message: '&b&lCombat &a<barsLeft>&c<barsPassed> &e&l<time> &b[sec]'
    # Symbol to use for the bar and how many times to repeat it. Other symbols ▊,▮,▯,|
    Symbol: '▊'
    Total Bars: 20
  Boss Bar:
    Enabled: false
    # You can use any PlaceholderAPI placeholders here
    Message: '&8&l[&c&lIn Combat&8&l] &e&l<time> seconds'
    # See here for bar color options - https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarColor.html
    BarColor: RED
    # See here for bar style options - https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarStyle.html
    BarStyle: SOLID
  Self Tag: false
  Untag Enemy: false
  EnderPearl:
    # If enabled, will retag the player when they throw an enderpearl
    Renew Tag: true
  Block:
    EnderPearls: false
    ChorusFruits: false
    Teleport: true
    Place Blocks: false
    Break Blocks: false
    Interact:
      Enabled: false
      # List of materials to block interaction, adding DOOR means all materials that end with DOOR like IRON_DOOR and so on
      # Enable this if you have sit plugins and need to block sitting on stairs, etc
      List:
        - 'DOOR'
        - 'BUTTON'
        - 'BED'
        - 'SLAB'
        - 'STAIRS'
        - 'CARPET'
    Elytra: false
    Riptide: true
    Eat: false
    Totem of Undying: false
    Open Inventory: false
    Enter Portal: false
    Commands:
      Enabled: true
      Whitelist: true
      Command List:
        - 'tell'
        - 'combattag'
  Commands On Tag:
    - '!CONSOLE examplecommand'
    - '!PLAYER examplecommand'
  Commands On Untag:
    - '!CONSOLE examplecommand'
    - '!PLAYER examplecommand'
  WorldGuard Exclusions:
    - 'example'
  Punishments:
    Punish On Kick:
      Enabled: true
      # If Match Kick Reason is enabled, the punishment will be applied only if the kick reason matches the list below
      Match Kick Reason: false
      Kick Reasons:
      - 'Kicked for spamming'
      - 'disconnect.spam'
    Money Penalty: 0.0
    Log To File: true
    Kill on Logout: true
    Spawn NPC:
      Enabled: false
      NPC Name: ''
      NPC Despawn Time: 30
      Block Login: true
      Targetable By Mobs: true
      Spawn On All Logouts: false
      WorldGuard Exclusions:
        - 'example'
    Drops On Death:
      Inventory: true
      Experience: true
      Armor: true
    Commands On PvPLog:
      - 'announce &6[&8PIXELS&6]&c %p tried to escape combat!'

# Should new players on your server be protected from PvP (If they want to PvP they can use /newbie disable)
Newbie Protection:
  Enabled: true
  # How many minutes should newbie protection last, persists through restarts
  Time(minutes): 10
  # If players should be allowed to remove their protection with /newbie disable
  Allow Player Disable: true
  # Block players from picking up items or place blocks while they have protection
  Block Pick Items: false
  Block Place Blocks: false
  Block Break Blocks: false
  # Protect newbies from all types of damage including PvE
  Protect From Everything: false
  Command Blacklist:
    - 'examplecommand'
    
# Here you can set a cooldown, in seconds, to any item such as golden apples and enchanted golden apples
# You can add other material types from here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
# If the item is not edible the cooldown will only be activated for right clicks
# Combat section sets cooldowns only while in combat, global means cooldowns will always apply
# You can disable the Minecraft builtin cooldown for an item by setting it to 0, like for enderpearls, or -1 for default
Item Cooldowns:
  Combat:
    ENDER_PEARL: -1
  Global:
    GOLDEN_APPLE: -1
    ENCHANTED_GOLDEN_APPLE: -1 

# Prevent player abuse by killing the same player several times to rise in rank or even just grief
# Example - If a player X kills player Y more than 5 times, it executes the commands defined(kick, jail, etc)
# In this case, it would check every 30 seconds for abusers
# Respawn Protection - After respawn, how many seconds should players be protected (0 to disable)
# Teleport Protection - After teleport, how many seconds should players be protected from all damage (0 to disable)
# WorldGuard Exclusions -> Name of regions where players will not get punished by kill abuse
# Command Cooldown After Death - After a player dies ONLY in PvP, they will have to wait x seconds before being able to use
# the commands under 'Commands'. This can prevent abuse like instantly going back and steal the drops or kill the player
# Set Time to 0 if you want to disable this cooldown
Kill Abuse:
  Enabled: false
  Max Kills: 5
  Time Limit: 30
  # Possible variables are <player> and <victim>
  Commands on Abuse:
    - 'kick <player> &cKill Abuse Is Not Allowed!'
  Respawn Protection: 3
  Teleport Protection: 0
  WorldGuard Exclusions:
    - 'example'
  Command Cooldown After Death:
    Time: 3
    Commands:
      - 'back'

# Section with settings triggered when a player kills another player
# Money Reward - Money won as reward, use less or equal to 1 for percentage like 0.05 for 5%, 1 for 100% (0 to disable)
# Money Penalty - Money lost on PvP death, use less or equal to 1 for percentage like 0.1 for 10%, 1 for 100% (0 to disable)
# Money Steal - Should the amount won from money reward be stolen from the dead player
# Lightning - Strike lightning when a player dies in PvP, the lightning doesn't make any damage to other players
# Extra Drops - List of items (amount,Material) to drop from a dead player (Like loot drops from monsters)
# For example 1,DIAMOND would drop 1 diamond on death
# WorldGuard Exclusions - WorldGuard regions where rewards, penalties and commands will not be executed
Player Kills:
  Money Reward: 0.0
  Money Penalty: 0.0
  Money Steal: false
  Death Effects:
    Lightning: false
  # Commands to execute on kill (<player> is the killer, <victim> is the victim, <item> is the item material in hand)
  Commands On Kill:
    - 'examplecommand <player> killed <victim> with <item>'
  WorldGuard Exclusions:
    - 'exampleregion'
  Extra Drops: []

# Section for PvP Toggle command - /pvp
# Players can't use the command unless they have permission
# Cooldown - How many seconds until players can use the command again
# State Cooldown - You have to wait x seconds to actually toggle PvP, to prevent abuses. This can be seen in games like GTA V
# NameTags - What should the player's prefix be when pvp is on/off
# You can write 'none' to disable one of the nametags, or set 'Enabled' to false to disable both
# Commands -> Command list to execute on PvP toggle, use '%p' for player name
# WorldGuard Overrides -> PvP Toggle is forcibly enabled on an attack in all regions with WG's pvp flag set to allow
# WorldGuard overrides region list -> PvP Toggle is forcibly enabled on an attack in the listed regions, regardless of the WG's pvp flag
PvP Toggle:
  Cooldown: 15
  # Displays a particle sphere around the player when he is attacked
  Protection Effect:
    Enabled: true
    # You can see other effects here but not all of them will work - https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
    # My suggestions are ENCHANTMENT_TABLE, REVERSE_PORTAL, SMALL_FLAME, DRIP_WATER, SOUL_FIRE_FLAME
    Particle: ENCHANTMENT_TABLE
    # Cooldown on the sphere particles, fine to leave at 0 for no cooldown
    Cooldown: 10
  State Cooldown:
    Enabled: false
    Time: 30
    Commands On Cooldown Start:
      - '!CONSOLE examplecommand <player>'
  NameTags:
    Enabled: false
    Prefix On: '&1'
    Prefix Off: '&2'
  # This setting runs every hour and applies a money fee to every player with PvP disabled, it's a very simplified system 
  # so it doesn't track how long PvP has been off for that player. Leave as 0 to disable
  PvP Disabled Money Fee: 0
  Commands PvP On:
    - 'examplecommand %p turned pvp on'
  Commands PvP Off:
    - 'examplecommand %p turned pvp off'
  WorldGuard Overrides: true
  WorldGuard Overrides Region List:
    - 'example'
    
# Section for the /pvpgrant command that gives temporary protection    
PvP Grant:
  # Block players from picking up items while they have protection
  Block Pick Items: false

# Section to configure interactions with other plugins
Plugin Hooks:
  CMI:
    # Should AFK players be protected from other players
    Protect AFK: true
  Essentials:
    # Should AFK players be protected from other players
    Protect AFK: true
  BountyHunters:
    # Disable PvP protection if the player has a bounty on themselves
    No Protection With Bounty: true
  Lands:
    # Disable PvP protection if the player is in a Lands war
    No Protection In War: true
  Kingdoms:
    # Disable PvP and newbie protection if the players are in an invasion
    No Protection In War: true
  SimpleClans:
    # Disable PvP and newbie protection if the players are in a SimpleClans war
    No Protection In War: true
  Towny:
    # Disable PvP and newbie protection if the players are in a siege war
    No Protection In War: true
    # Essentially only pushes back if a town is peaceful, it ignores if the town PvP is on or off, can be useful to prevent traps
    Pushback on Peaceful: false
  # This only works if you have the TAB plugin, disabling both options will make PvPManager use normal scoreboard teams
  TAB:
    # Show combat prefix/suffix in the playerlist (tab)
    Show In Tab: true
    # Show combat prefix/suffix above the player's head
    Show Above Player: true
  ajQueue:
    # This requires a custom version of ajQueue made by me, prevents combat loggers from getting punished if in queue
    # List of destination servers that won't cause the player to be punished on combat log
    Servers:
      - lobby

Database:
  # Database type, supported databases: SQLite or MySQL
  Type: SQLite
  # Only fill this section if using MySQL
  MySQL:
    Host: 127.0.0.1
    Port: 3306
    Username: root
    Password: '12345'
    Database: minecraft

# Should PvPManager be allowed to check for updates and tell you about them
Update Check:
  Enabled: true

# Potions considered harmful, players will be tagged by them and protected from them
# See list here https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionEffectType.html
Harmful Potions:
  - SLOW
  - SLOWNESS # SLOW 1.20.5+
  - SLOW_DIGGING
  - MINING_FATIGUE # SLOW_DIGGING 1.20.5+
  - CONFUSION
  - NAUSEA # CONFUSION 1.20.5+
  - BLINDNESS
  - HUNGER
  - WEAKNESS
  - POISON
  - WITHER
  - GLOWING
  - LEVITATION
  - UNLUCK
  - BAD_OMEN
  - INFESTED

Debug Mode: false

# Informs PvPManager if the config is updated, do not touch it unless you want to reset the config
Config Version: 110
Database Version: 1

```

**Comment by ChanceSD** [comment]
Set

> NameTag Prefix: '&4&l&c'

 to empty like

> NameTag Prefix: ''

To have nametags change when in combat consider using the TAB plugin since PvPManager hooks into it and shouldn't cause those issues. Or if you don't need that feature then just leave it empty like I said above.
